

server {
    root  /home/aayad/Desktop/wb-ser-mac/site;
    listen 127.0.0.1:8080;
    server_name site1;

    root /home/mohidbel/Desktop/web/site;
    index index.html;
    	location / {
		# autoindex on;
		# index index.html;
		limit_except GET POST;
		CGI on;
		upload on;
		uploadPath /home/aayad/Desktop/wb-ser-mac/site/Download; 
		cgiPath .py  /usr/bin/python3;
		cgiPath .php  /usr/bin/php;
		cgiPath .sh /bin/bash;	
		# root ./site/; 
        }
}

server {
    listen 127.0.0.1:8081;
    server_name site2;

    root /home/mohidbel/Desktop/web/site;
    index home.html;
}