server {
	listen 0.0.0.0:8441  ;
	autoindex on;
	server_name mayserve;
	# client_max_body_size 	100000000M;
	CGI on;
	upload on;
	cgiPath .py /usr/bin/python3;
	
	uploadPath /workspaces/webserver-42/site/Download;
	location / {
		# return 300;
		autoindex on;
		limit_except  GET POST DELETE;
		# index dasdasdsa;
		CGI on;
		upload on;
		cgiPath .py  /usr/bin/python3;
		uploadPath /workspaces/webserver-42/site; 
		cgiPath .php  /usr/php;
		cgiPath .sh /bin/bash;
		cgiPath .sh /bin/bash;
		root /workspaces/webserver-42/site;
	}

	location /find_images {
		root /home/zel-yama/Desktop/javascript-learning-/30_projectsJava/image_search;
		limit_except  GET   ;
		CGI on;
		cgiPath .py /usr/bin/php;

	}


	location /upload {

		error_page 500 /errors/500.html;
		limit_except POST;
		root /tmp/uploads;
	}
	location /mysite{
		root /home/zel-yama/mysite;
	
		index index.html;
		upload on;
		

	}

}