server {
	listen localhost:8442  ;
	autoindex on;
	server_name mayserve;
	client_max_body_size 	10G;
	CGI on;
	upload on;
	cgiPath .py /usr/bin/python3;
	cgiPath .bla /workspaces/webserver-42/cgi_tester;
	uploadPath /workspaces/webserver-42/site/Download;
	location / {
		# return 300;
		# autoindex off;
		limit_except  GET ;
		#index index.html;
		CGI on;
		upload on;
		cgiPath .py  /usr/bin/python3;
		uploadPath /workspaces/webserver-42/site; 
		cgiPath .php  /usr/php;
		cgiPath .sh /bin/bash;
		cgiPath .sh /bin/bash;
		root /workspaces/webserver-42/YoupiBanane;
	}

	location /find_images {
		root /home/zel-yama/Desktop/javascript-learning-/30_projectsJava/image_search;
		limit_except  GET   ;
		CGI on;
		cgiPath .py /usr/bin/php;
		 #i should this -> line ;
	}
	
	location /post_body {
		root /workspaces/webserver-42/YoupiBanane;
		limit_except GET POST;
		client_max_body_size 100;
		CGI on;
	}
	location /directory {
		
		root /workspaces/webserver-42/YoupiBanane;
		limit_except  GET   ;
		index youpi.bad_extension;


	}
	location /bla {
		limit_except POST;
		CGI on;
		cgiPath .bla /workspaces/webserver-42/cgi_tester;
	}
	location /upload {

		error_page 500 /errors/500.html;
		limit_except POST;
		root /tmp/uploads;
	}
	location /mysite{
		root /home/zel-yama/mysite;
	
		index index.html;
		upload on;
		

	}

}
