server {
	listen localhost:8442  ;
	autoindex on;
	server_name mayserve;
	client_max_body_size 	10G;
	CGI on;
	upload on;
	cgiPath .py /usr/bin/python3;
	cgiPath .php  /usr/php;
	index index.html;
	uploadPath /home/zel-yama/Desktop/webserver-42/site/Download;

	location / {
		limit_except  GET   ;
		upload on;
		uploadPath /home/goinfre/; 
		root /home/zel-yama/Desktop/webserver-42/site;
	}
	
}
